spring:
  profiles:
    active: prod
  config:
    activate:
      on-profile: dev

mybatis-plus:
  mapper-locations: classpath*:top/hcode/hoj/dao/xml/**Mapper.xml
  type-aliases-package: top.hcode.hoj.pojo.entity
  configuration:
    cache-enabled: false
  # 关闭打印 mybatis-plus 的 LOGO
  global-config:
    banner: false

# 消费者将要去访问的微服务名称（注册成功进入nacos的微服务提供者）
service-url:
  name: hoj-judgeserver # 服务名
